site_name: 'DevOps Wiki - Comunidade TILabs'
theme:
  name: 'material'
nav:
  - 'Home': index.md
  - 'SRE':
      - '[base] SRE I': sre/sre1.md
      - '[base] SRE II': sre/sre2.md
      - '[base] SRE III': sre/sre3.md
  - 'Especialista':
      - 'Senior SRE': sre/senior_sre.md
      - 'Staff SRE': sre/staff_sre.md
